### ISSUE TITLE
海天报错

### ISSUE THREAD

**Issue by jiuchu** [yang7758258/ohhh_QL-Script#2]
getaddrinfo ENOTFOUND cmallapi.haday.cn"

❗️vx海天美味馆,错误!

SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at SignTask (/ql/scripts/htmwg.js:119:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async userTask (/ql/scripts/htmwg.js:72:5)
    at async main (/ql/scripts/htmwg.js:60:9)
    at async /ql/scripts/htmwg.js:25:5

[liulanjifen]请求错误(ENOTFOUND)，重试第1次
是按照格式抓的

**Comment by yang7758258** [comment]
青龙里装 got 依赖再测试下

**Comment by jiuchu** [comment]
> 青龙里装 got 依赖再测试下

刚刚安装了还是一样的 给个邮箱我发你测试下 看看是不是账号的问题吧

**Comment by yang7758258** [comment]
刚更新了，你重新拉库试试

**Comment by ahang19981** [comment]
还是报错  问题是在签到这里获取的result打印是undefined  但是我使用postman 测试可以通 不知道什么情况

**Comment by yang7758258** [comment]
> 还是报错 问题是在签到这里获取的result打印是undefined 但是我使用postman 测试可以通 不知道什么情况

你看下签到上了不 签到上了就不影响
